### ISSUE TITLE
Optifine?

### ISSUE THREAD

**Issue by CrossWayIstaken** [FA1C0Nl-lAWK/Wyattcraft-Modpack#2]
I don't think you can redistribute optifine without permission as said on their FAQ.
`Can I include OptiFine in my modpack?
Generally no, unless you have an explicit permission from us. `

**Comment by FA1C0Nl-lAWK** [comment]
oh...

**Comment by CrossWayIstaken** [comment]
Closing since it looks like it was resolved.
